#!/bin/sh

GIT_DIR=$(pwd)
cd /tmp
rm -rf sitincator
git clone $GIT_DIR
cd sitincator
NODE_ENV=production npm install

rm -rf Sitincator-linux-armv7l
npm run build:pi
rm Sitincator-linux-armv7l/resources/app/{config,credentials}/*
zip -y Sitincator-linux-armv7l.zip Sitincator-linux-armv7l/*